'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Recursos
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ContaHogar.Recursos", GetType(Recursos).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Apuntes Periódicos.
    '''</summary>
    Friend Shared ReadOnly Property ApuntesPeriodicos() As String
        Get
            Return ResourceManager.GetString("ApuntesPeriodicos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a creado correctamente.
    '''</summary>
    Friend Shared ReadOnly Property CreadoCorrectamente() As String
        Get
            Return ResourceManager.GetString("CreadoCorrectamente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al buscar el ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlBuscarEjercicio() As String
        Get
            Return ResourceManager.GetString("ErrorAlBuscarEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al crear el ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlCrearEjercicio() As String
        Get
            Return ResourceManager.GetString("ErrorAlCrearEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al eliminar los registros SALDO del Ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlEliminarSaldo() As String
        Get
            Return ResourceManager.GetString("ErrorAlEliminarSaldo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property Exercici() As String
        Get
            Return ResourceManager.GetString("Exercici", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Filtrado).
    '''</summary>
    Friend Shared ReadOnly Property Filtrado() As String
        Get
            Return ResourceManager.GetString("Filtrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Introducción de Apuntes.
    '''</summary>
    Friend Shared ReadOnly Property IntroducirApuntes() As String
        Get
            Return ResourceManager.GetString("IntroducirApuntes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a &quot;Software en Modo Demo. Por favor active el software para quitar esta advertencia.&quot;.
    '''</summary>
    Friend Shared ReadOnly Property LblAvisoActivacion() As String
        Get
            Return ResourceManager.GetString("LblAvisoActivacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Hay Conceptos Varios, Seleccionados.
    '''Filtrar Primero por Cuentas y Fechas,
    '''después por Conceptos Varios.
    '''</summary>
    Friend Shared ReadOnly Property MsgAviso1() As String
        Get
            Return ResourceManager.GetString("MsgAviso1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay ninguna Coincidencia con los datos Introducidos.
    '''</summary>
    Friend Shared ReadOnly Property MsgDatos1() As String
        Get
            Return ResourceManager.GetString("MsgDatos1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay más Registros que Coincidan con los datos Introducidos.
    '''</summary>
    Friend Shared ReadOnly Property MsgDatos2() As String
        Get
            Return ResourceManager.GetString("MsgDatos2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Formato de fecha no válido.
    '''</summary>
    Friend Shared ReadOnly Property MsgErrorFecha() As String
        Get
            Return ResourceManager.GetString("MsgErrorFecha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a En Espera ....
    '''</summary>
    Friend Shared ReadOnly Property MsgEspera() As String
        Get
            Return ResourceManager.GetString("MsgEspera", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fila Primera Seleccionada.
    '''</summary>
    Friend Shared ReadOnly Property MsgFila1() As String
        Get
            Return ResourceManager.GetString("MsgFila1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fila Ultima Seleccionada.
    '''</summary>
    Friend Shared ReadOnly Property MsgFila2() As String
        Get
            Return ResourceManager.GetString("MsgFila2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Los Saldos iniciales, NO se pueden Borrar.
    '''</summary>
    Friend Shared ReadOnly Property MsgSaldos1() As String
        Get
            Return ResourceManager.GetString("MsgSaldos1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Los Saldos iniciales, NO se pueden Editar.
    '''</summary>
    Friend Shared ReadOnly Property MsgSaldos2() As String
        Get
            Return ResourceManager.GetString("MsgSaldos2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aviso de Filtros.
    '''</summary>
    Friend Shared ReadOnly Property MsgText1() As String
        Get
            Return ResourceManager.GetString("MsgText1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Introducción de Apuntes.
    '''</summary>
    Friend Shared ReadOnly Property MsgText2() As String
        Get
            Return ResourceManager.GetString("MsgText2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Varios Conceptos Seleccionados.
    '''</summary>
    Friend Shared ReadOnly Property MsgText3() As String
        Get
            Return ResourceManager.GetString("MsgText3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a VARIOS CONCEPTOS.
    '''</summary>
    Friend Shared ReadOnly Property MsgText4() As String
        Get
            Return ResourceManager.GetString("MsgText4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No existen registros del.
    '''</summary>
    Friend Shared ReadOnly Property NoExistenRegistros() As String
        Get
            Return ResourceManager.GetString("NoExistenRegistros", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Registro Apunte Periódico, Borrado !!!.
    '''</summary>
    Friend Shared ReadOnly Property RegistroApuntePeriódicoBorrado() As String
        Get
            Return ResourceManager.GetString("RegistroApuntePeriódicoBorrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a se creará ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property SeCrearaEjercicio() As String
        Get
            Return ResourceManager.GetString("SeCrearaEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Sin Filtrar).
    '''</summary>
    Friend Shared ReadOnly Property SinFiltrar() As String
        Get
            Return ResourceManager.GetString("SinFiltrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ContaHogar 3.0.
    '''</summary>
    Friend Shared ReadOnly Property TitolApp() As String
        Get
            Return ResourceManager.GetString("TitolApp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Añadir Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAñadir() As String
        Get
            Return ResourceManager.GetString("ToolTipAñadir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Anterior Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAnterior() As String
        Get
            Return ResourceManager.GetString("ToolTipAnterior", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aplica el filtro a los Registros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAplicarFiltro() As String
        Get
            Return ResourceManager.GetString("ToolTipAplicarFiltro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aumentar tamaño de fuente.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAumentar() As String
        Get
            Return ResourceManager.GetString("ToolTipAumentar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Buscar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipBuscar() As String
        Get
            Return ResourceManager.GetString("ToolTipBuscar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Activar la Calculadora.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipCalculadora() As String
        Get
            Return ResourceManager.GetString("ToolTipCalculadora", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Abrir listado de Conceptos para múltiple selección.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipChekedList() As String
        Get
            Return ResourceManager.GetString("ToolTipChekedList", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Editar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEditar() As String
        Get
            Return ResourceManager.GetString("ToolTipEditar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eliminar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEliminar() As String
        Get
            Return ResourceManager.GetString("ToolTipEliminar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Suprimir las Filas Seleccionadas de la Parrilla
    '''No se Eliminan de la Base de Datos.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEliminaSeleccion() As String
        Get
            Return ResourceManager.GetString("ToolTipEliminaSeleccion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Exportar Apuntes a Excel.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipExcel() As String
        Get
            Return ResourceManager.GetString("ToolTipExcel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Filtra por Descripción.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipF5() As String
        Get
            Return ResourceManager.GetString("ToolTipF5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Refrescar la Parrilla Apuntes y Quitar Filtros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipF6() As String
        Get
            Return ResourceManager.GetString("ToolTipF6", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Activar o Desactivar Acceso a Fechas anteriores al Ejercicio Actual.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipFechas() As String
        Get
            Return ResourceManager.GetString("ToolTipFechas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mostrar Gráficos.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipGraficos() As String
        Get
            Return ResourceManager.GetString("ToolTipGraficos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Imprimir.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipImprimir() As String
        Get
            Return ResourceManager.GetString("ToolTipImprimir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Con Tecla Suprimir: Elimina filas seleccionadas
    '''Con F5: Filtra por Descripción
    '''Con F6: Refresca la Parrilla Apuntes y Quita Filtros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipLabelApuntes() As String
        Get
            Return ResourceManager.GetString("ToolTipLabelApuntes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Con Tecla Esc: Cerrar Listado.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipListBox() As String
        Get
            Return ResourceManager.GetString("ToolTipListBox", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Restaurar tamaño de fuente.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipNormal() As String
        Get
            Return ResourceManager.GetString("ToolTipNormal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Primer Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipPrimero() As String
        Get
            Return ResourceManager.GetString("ToolTipPrimero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Quitar el filtro a los Registros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipQuitarFiltro() As String
        Get
            Return ResourceManager.GetString("ToolTipQuitarFiltro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Salir/Cerrar Ventana.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSalir() As String
        Get
            Return ResourceManager.GetString("ToolTipSalir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Pulsar para Seguir Buscando o F3.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSeguirBuscando() As String
        Get
            Return ResourceManager.GetString("ToolTipSeguirBuscando", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Siguiente Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSiguiente() As String
        Get
            Return ResourceManager.GetString("ToolTipSiguiente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Traspasar de una Cuenta a Otra.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipTraspasar() As String
        Get
            Return ResourceManager.GetString("ToolTipTraspasar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Ultimo Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipUltimo() As String
        Get
            Return ResourceManager.GetString("ToolTipUltimo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Traspaso entre Cuentas.
    '''</summary>
    Friend Shared ReadOnly Property TraspasoCuentas() As String
        Get
            Return ResourceManager.GetString("TraspasoCuentas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ver Apuntes.
    '''</summary>
    Friend Shared ReadOnly Property VerApuntes() As String
        Get
            Return ResourceManager.GetString("VerApuntes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión.
    '''</summary>
    Friend Shared ReadOnly Property Versio() As String
        Get
            Return ResourceManager.GetString("Versio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión disponible:.
    '''</summary>
    Friend Shared ReadOnly Property VersionDisponible() As String
        Get
            Return ResourceManager.GetString("VersionDisponible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión Instalada:.
    '''</summary>
    Friend Shared ReadOnly Property VersionInstalada() As String
        Get
            Return ResourceManager.GetString("VersionInstalada", resourceCulture)
        End Get
    End Property
End Class
