'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Recursos
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ContaHogar.Recursos", GetType(Recursos).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a 1er Cobro.
    '''</summary>
    Friend Shared ReadOnly Property _1erCobro() As String
        Get
            Return ResourceManager.GetString("1erCobro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a 1er Pago.
    '''</summary>
    Friend Shared ReadOnly Property _1erPago() As String
        Get
            Return ResourceManager.GetString("1erPago", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error.
    '''</summary>
    Friend Shared ReadOnly Property _Error() As String
        Get
            Return ResourceManager.GetString("Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Acción Cancelada.
    '''</summary>
    Friend Shared ReadOnly Property AccionCancelada() As String
        Get
            Return ResourceManager.GetString("AccionCancelada", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Actualización Completada.
    '''</summary>
    Friend Shared ReadOnly Property ActualizacionCompletada() As String
        Get
            Return ResourceManager.GetString("ActualizacionCompletada", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Actualizar Software.
    '''</summary>
    Friend Shared ReadOnly Property ActualizarSoftware() As String
        Get
            Return ResourceManager.GetString("ActualizarSoftware", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Quieres actualizar a la Versión.
    '''</summary>
    Friend Shared ReadOnly Property ActualizarVersion() As String
        Get
            Return ResourceManager.GetString("ActualizarVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a AGUA.
    '''</summary>
    Friend Shared ReadOnly Property AGUA() As String
        Get
            Return ResourceManager.GetString("AGUA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ahora, se descargará la actualización.
    '''</summary>
    Friend Shared ReadOnly Property AhoraDescargaActualizacion() As String
        Get
            Return ResourceManager.GetString("AhoraDescargaActualizacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ALIMENTACION.
    '''</summary>
    Friend Shared ReadOnly Property ALIMENTACION() As String
        Get
            Return ResourceManager.GetString("ALIMENTACION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Atención.
    '''</summary>
    Friend Shared ReadOnly Property Atencion() As String
        Get
            Return ResourceManager.GetString("Atencion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aviso.
    '''</summary>
    Friend Shared ReadOnly Property Aviso() As String
        Get
            Return ResourceManager.GetString("Aviso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Los conceptos predeterminados del sistema están protegidos contra modificaciones, si no se va a usar se puede Eliminar.
    '''</summary>
    Friend Shared ReadOnly Property AvisoConceptoProtegido() As String
        Get
            Return ResourceManager.GetString("AvisoConceptoProtegido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aviso: No existen apuntes registrados para la cuenta seleccionada en este ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property AvisoNoHayRegistrosEjercicio() As String
        Get
            Return ResourceManager.GetString("AvisoNoHayRegistrosEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Los tipos de cuentas predeterminados del sistema están protegidos contra modificaciones, si no se va a usar se puede Eliminar.
    '''</summary>
    Friend Shared ReadOnly Property AvisoTipoCuentaProtegido() As String
        Get
            Return ResourceManager.GetString("AvisoTipoCuentaProtegido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ayuda.
    '''</summary>
    Friend Shared ReadOnly Property Ayuda() As String
        Get
            Return ResourceManager.GetString("Ayuda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Copia de Seguridad.
    '''</summary>
    Friend Shared ReadOnly Property Backup() As String
        Get
            Return ResourceManager.GetString("Backup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Copia de Seguridad realizado satisfactoriamente.
    '''Ahora, se descargará la actualización.
    '''</summary>
    Friend Shared ReadOnly Property BackupSatisfactorioBuscarActualizacio() As String
        Get
            Return ResourceManager.GetString("BackupSatisfactorioBuscarActualizacio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a BBVA.
    '''</summary>
    Friend Shared ReadOnly Property BBVA() As String
        Get
            Return ResourceManager.GetString("BBVA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aceptar.
    '''</summary>
    Friend Shared ReadOnly Property BotonAceptar() As String
        Get
            Return ResourceManager.GetString("BotonAceptar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No.
    '''</summary>
    Friend Shared ReadOnly Property BotonNo() As String
        Get
            Return ResourceManager.GetString("BotonNo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Sí.
    '''</summary>
    Friend Shared ReadOnly Property BotonSi() As String
        Get
            Return ResourceManager.GetString("BotonSi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Añade, Edita, Borra o Consulta Conceptos.
    '''</summary>
    Friend Shared ReadOnly Property BtnConcepto() As String
        Get
            Return ResourceManager.GetString("BtnConcepto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Añade, Edita, Borra o Consulta Cuentas Bancarias.
    '''</summary>
    Friend Shared ReadOnly Property BtnCuenta() As String
        Get
            Return ResourceManager.GetString("BtnCuenta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CUENTA CAJA EFECTIVO.
    '''</summary>
    Friend Shared ReadOnly Property CAJA_EFECTIVO() As String
        Get
            Return ResourceManager.GetString("CAJA_EFECTIVO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CANAL+.
    '''</summary>
    Friend Shared ReadOnly Property CANAL_() As String
        Get
            Return ResourceManager.GetString("CANAL+", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CASA.
    '''</summary>
    Friend Shared ReadOnly Property CASA() As String
        Get
            Return ResourceManager.GetString("CASA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Se cerrará el programa para iniciar con el Ejercicio Actual.
    '''</summary>
    Friend Shared ReadOnly Property CerrarApp() As String
        Get
            Return ResourceManager.GetString("CerrarApp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CLIENTE.
    '''</summary>
    Friend Shared ReadOnly Property CLIENTE00() As String
        Get
            Return ResourceManager.GetString("CLIENTE00", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Código.
    '''</summary>
    Friend Shared ReadOnly Property Codigo() As String
        Get
            Return ResourceManager.GetString("Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a COMUNIDAD.
    '''</summary>
    Friend Shared ReadOnly Property COMUNIDAD() As String
        Get
            Return ResourceManager.GetString("COMUNIDAD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CON.
    '''</summary>
    Friend Shared ReadOnly Property CON() As String
        Get
            Return ResourceManager.GetString("CON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Concepto.
    '''</summary>
    Friend Shared ReadOnly Property Concepto() As String
        Get
            Return ResourceManager.GetString("Concepto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Conceptos.
    '''</summary>
    Friend Shared ReadOnly Property Conceptos() As String
        Get
            Return ResourceManager.GetString("Conceptos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El concepto y todos sus registros vinculados han sido eliminados correctamente.
    '''</summary>
    Friend Shared ReadOnly Property ConceptoYRegistrosEliminados() As String
        Get
            Return ResourceManager.GetString("ConceptoYRegistrosEliminados", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Confirmar Borrado Múltiple.
    '''</summary>
    Friend Shared ReadOnly Property ConfirmarBorrado() As String
        Get
            Return ResourceManager.GetString("ConfirmarBorrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Control de Seguridad Windows.
    '''</summary>
    Friend Shared ReadOnly Property ControlSeguridadWindows() As String
        Get
            Return ResourceManager.GetString("ControlSeguridadWindows", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cuenta.
    '''</summary>
    Friend Shared ReadOnly Property Cuenta() As String
        Get
            Return ResourceManager.GetString("Cuenta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CUENTA CORRIENTE.
    '''</summary>
    Friend Shared ReadOnly Property CUENTA_CORRIENTE() As String
        Get
            Return ResourceManager.GetString("CUENTA_CORRIENTE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CUENTA VIVIENDA.
    '''</summary>
    Friend Shared ReadOnly Property CUENTA_VIVIENDA() As String
        Get
            Return ResourceManager.GetString("CUENTA_VIVIENDA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cuentas.
    '''</summary>
    Friend Shared ReadOnly Property Cuentas() As String
        Get
            Return ResourceManager.GetString("Cuentas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a DECESOS.
    '''</summary>
    Friend Shared ReadOnly Property DECESOS() As String
        Get
            Return ResourceManager.GetString("DECESOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Agua.
    '''</summary>
    Friend Shared ReadOnly Property Desc_AGUA() As String
        Get
            Return ResourceManager.GetString("Desc_AGUA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Comida.
    '''</summary>
    Friend Shared ReadOnly Property Desc_ALIMENTACION() As String
        Get
            Return ResourceManager.GetString("Desc_ALIMENTACION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a BBVA.
    '''</summary>
    Friend Shared ReadOnly Property Desc_BBVA() As String
        Get
            Return ResourceManager.GetString("Desc_BBVA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Efectivo en casa.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CAJA_EFECTIVO() As String
        Get
            Return ResourceManager.GetString("Desc_CAJA_EFECTIVO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Canal Plus Digital.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CANAL_() As String
        Get
            Return ResourceManager.GetString("Desc_CANAL+", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Utiles Casa.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CASA() As String
        Get
            Return ResourceManager.GetString("Desc_CASA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cliente.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CLIENTE00() As String
        Get
            Return ResourceManager.GetString("Desc_CLIENTE00", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Comunidad Parking.
    '''</summary>
    Friend Shared ReadOnly Property Desc_COMUNIDAD() As String
        Get
            Return ResourceManager.GetString("Desc_COMUNIDAD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cuenta Corriente Bancaria.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CUENTA_CORRIENTE() As String
        Get
            Return ResourceManager.GetString("Desc_CUENTA_CORRIENTE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cuenta Vivienda Habitual.
    '''</summary>
    Friend Shared ReadOnly Property Desc_CUENTA_VIVIENDA() As String
        Get
            Return ResourceManager.GetString("Desc_CUENTA_VIVIENDA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Decesos.
    '''</summary>
    Friend Shared ReadOnly Property Desc_DECESOS() As String
        Get
            Return ResourceManager.GetString("Desc_DECESOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Dinero en Efectivo.
    '''</summary>
    Friend Shared ReadOnly Property Desc_EFECTIVO() As String
        Get
            Return ResourceManager.GetString("Desc_EFECTIVO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El Corte Inglés.
    '''</summary>
    Friend Shared ReadOnly Property Desc_EL_CORTE_INGLES() As String
        Get
            Return ResourceManager.GetString("Desc_EL_CORTE_INGLES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Estética y Peluquería.
    '''</summary>
    Friend Shared ReadOnly Property Desc_ESTETICA() As String
        Get
            Return ResourceManager.GetString("Desc_ESTETICA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Farmacia.
    '''</summary>
    Friend Shared ReadOnly Property Desc_FARMACIA() As String
        Get
            Return ResourceManager.GetString("Desc_FARMACIA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fondo de Inversión Banco.
    '''</summary>
    Friend Shared ReadOnly Property Desc_FONDO_DE_INVERSION() As String
        Get
            Return ResourceManager.GetString("Desc_FONDO_DE_INVERSION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Gas Natural.
    '''</summary>
    Friend Shared ReadOnly Property Desc_GAS_NATURAL() As String
        Get
            Return ResourceManager.GetString("Desc_GAS_NATURAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Gasolina o Gas-Oil.
    '''</summary>
    Friend Shared ReadOnly Property Desc_GASOLINA() As String
        Get
            Return ResourceManager.GetString("Desc_GASOLINA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Gastos Bancarios.
    '''</summary>
    Friend Shared ReadOnly Property Desc_GASTOS_BANCARIOS() As String
        Get
            Return ResourceManager.GetString("Desc_GASTOS_BANCARIOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Hacienda Pública.
    '''</summary>
    Friend Shared ReadOnly Property Desc_HACIENDA() As String
        Get
            Return ResourceManager.GetString("Desc_HACIENDA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Impuesto Basuras.
    '''</summary>
    Friend Shared ReadOnly Property Desc_IMPUESTO_1() As String
        Get
            Return ResourceManager.GetString("Desc_IMPUESTO_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Impuesto Ibi.
    '''</summary>
    Friend Shared ReadOnly Property Desc_IMPUESTO_2() As String
        Get
            Return ResourceManager.GetString("Desc_IMPUESTO_2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Impuesto Vehículo.
    '''</summary>
    Friend Shared ReadOnly Property Desc_IMPUESTO_3() As String
        Get
            Return ResourceManager.GetString("Desc_IMPUESTO_3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Impuesto Moto.
    '''</summary>
    Friend Shared ReadOnly Property Desc_IMPUESTO_4() As String
        Get
            Return ResourceManager.GetString("Desc_IMPUESTO_4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Impuesto CO2.
    '''</summary>
    Friend Shared ReadOnly Property Desc_IMPUESTO_5() As String
        Get
            Return ResourceManager.GetString("Desc_IMPUESTO_5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Intereses Bancarios.
    '''</summary>
    Friend Shared ReadOnly Property Desc_INTERESES() As String
        Get
            Return ResourceManager.GetString("Desc_INTERESES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Plantas.
    '''</summary>
    Friend Shared ReadOnly Property Desc_JARDIN() As String
        Get
            Return ResourceManager.GetString("Desc_JARDIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Compañía Luz.
    '''</summary>
    Friend Shared ReadOnly Property Desc_LUZ() As String
        Get
            Return ResourceManager.GetString("Desc_LUZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Diversión y Entretenimiento.
    '''</summary>
    Friend Shared ReadOnly Property Desc_OCIO() As String
        Get
            Return ResourceManager.GetString("Desc_OCIO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a OPENBANK.
    '''</summary>
    Friend Shared ReadOnly Property Desc_OPENBANK() As String
        Get
            Return ResourceManager.GetString("Desc_OPENBANK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Pensión o Sueldo.
    '''</summary>
    Friend Shared ReadOnly Property Desc_PENSION() As String
        Get
            Return ResourceManager.GetString("Desc_PENSION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Plan de Pensiones.
    '''</summary>
    Friend Shared ReadOnly Property Desc_PLAN_DE_PENSIONES() As String
        Get
            Return ResourceManager.GetString("Desc_PLAN_DE_PENSIONES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Plan de Pensiones.
    '''</summary>
    Friend Shared ReadOnly Property Desc_PLAN_PENSIONES() As String
        Get
            Return ResourceManager.GetString("Desc_PLAN_PENSIONES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Regularización de Ingresos.
    '''</summary>
    Friend Shared ReadOnly Property Desc_REGULARIZACION_1() As String
        Get
            Return ResourceManager.GetString("Desc_REGULARIZACION_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Regularización de Gastos.
    '''</summary>
    Friend Shared ReadOnly Property Desc_REGULARIZACION_2() As String
        Get
            Return ResourceManager.GetString("Desc_REGULARIZACION_2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ropa y Zapatos.
    '''</summary>
    Friend Shared ReadOnly Property Desc_ROPA() As String
        Get
            Return ResourceManager.GetString("Desc_ROPA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Saldo inicial.
    '''</summary>
    Friend Shared ReadOnly Property Desc_SALDO() As String
        Get
            Return ResourceManager.GetString("Desc_SALDO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Seguro Casa.
    '''</summary>
    Friend Shared ReadOnly Property Desc_SEGURO_CASA() As String
        Get
            Return ResourceManager.GetString("Desc_SEGURO_CASA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Seguro Coche.
    '''</summary>
    Friend Shared ReadOnly Property Desc_SEGURO_COCHE() As String
        Get
            Return ResourceManager.GetString("Desc_SEGURO_COCHE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Seguro Moto.
    '''</summary>
    Friend Shared ReadOnly Property Desc_SEGURO_MOTO() As String
        Get
            Return ResourceManager.GetString("Desc_SEGURO_MOTO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tarjeta de Crédito.
    '''</summary>
    Friend Shared ReadOnly Property Desc_TARJETA_DE_CREDITO() As String
        Get
            Return ResourceManager.GetString("Desc_TARJETA_DE_CREDITO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Teléfono.
    '''</summary>
    Friend Shared ReadOnly Property Desc_TELEFONO() As String
        Get
            Return ResourceManager.GetString("Desc_TELEFONO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Traspaso entre cuentas.
    '''</summary>
    Friend Shared ReadOnly Property Desc_TRASPASO() As String
        Get
            Return ResourceManager.GetString("Desc_TRASPASO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Varios sin Justificar.
    '''</summary>
    Friend Shared ReadOnly Property Desc_VARIOS() As String
        Get
            Return ResourceManager.GetString("Desc_VARIOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Coche y Moto.
    '''</summary>
    Friend Shared ReadOnly Property Desc_VEHICULOS() As String
        Get
            Return ResourceManager.GetString("Desc_VEHICULOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Se ha descargado la actualización.
    '''</summary>
    Friend Shared ReadOnly Property DescargadaActualizacion() As String
        Get
            Return ResourceManager.GetString("DescargadaActualizacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Descripción.
    '''</summary>
    Friend Shared ReadOnly Property Descripcion() As String
        Get
            Return ResourceManager.GetString("Descripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Desde.
    '''</summary>
    Friend Shared ReadOnly Property Desde() As String
        Get
            Return ResourceManager.GetString("Desde", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Destino.
    '''</summary>
    Friend Shared ReadOnly Property Destino() As String
        Get
            Return ResourceManager.GetString("Destino", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a días.
    '''</summary>
    Friend Shared ReadOnly Property dias() As String
        Get
            Return ResourceManager.GetString("dias", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CAJA EFECTIVO.
    '''</summary>
    Friend Shared ReadOnly Property EFECTIVO() As String
        Get
            Return ResourceManager.GetString("EFECTIVO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property Ejercicio() As String
        Get
            Return ResourceManager.GetString("Ejercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a EL CORTE INGLES.
    '''</summary>
    Friend Shared ReadOnly Property EL_CORTE_INGLES() As String
        Get
            Return ResourceManager.GetString("EL_CORTE_INGLES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a En Curso....
    '''</summary>
    Friend Shared ReadOnly Property EnCurso() As String
        Get
            Return ResourceManager.GetString("EnCurso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El antivirus o la protección de Windows está bloqueando el acceso a Mis Documentos.
    '''Por favor, añade este programa a la lista de exclusiones
    '''o permite el acceso controlado a carpetas para poder usar ContaHogar 3.0 Premium..
    '''</summary>
    Friend Shared ReadOnly Property Error_Permisos_Antivirus() As String
        Get
            Return ResourceManager.GetString("Error_Permisos_Antivirus", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al actualizar el apunte.
    '''</summary>
    Friend Shared ReadOnly Property ErrorActualizarApunte() As String
        Get
            Return ResourceManager.GetString("ErrorActualizarApunte", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al buscar el ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlBuscarEjercicio() As String
        Get
            Return ResourceManager.GetString("ErrorAlBuscarEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al crear el ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlCrearEjercicio() As String
        Get
            Return ResourceManager.GetString("ErrorAlCrearEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al ejecutar.
    '''</summary>
    Friend Shared ReadOnly Property ErrorAlEjecutar() As String
        Get
            Return ResourceManager.GetString("ErrorAlEjecutar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al ejecutar el asiento automático.
    '''</summary>
    Friend Shared ReadOnly Property ErrorApuntePeriodico() As String
        Get
            Return ResourceManager.GetString("ErrorApuntePeriodico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se pudo encontrar el archivo del manual de ayuda seleccionado en su carpeta de Documentos local.
    '''</summary>
    Friend Shared ReadOnly Property ErrorArchivoAyudaNoEncontrado() As String
        Get
            Return ResourceManager.GetString("ErrorArchivoAyudaNoEncontrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se pudo encontrar el archivo de Política de Privacidad en su carpeta de Documentos local.
    '''</summary>
    Friend Shared ReadOnly Property ErrorArchivoPrivacidadNoEncontrado() As String
        Get
            Return ResourceManager.GetString("ErrorArchivoPrivacidadNoEncontrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al realizar la Copia de Seguridad de la Base de Datos,
    '''revise que no exista otra Copia con el mismo nombre o
    '''que el archivo no esté abierto.
    '''</summary>
    Friend Shared ReadOnly Property ErrorBackup() As String
        Get
            Return ResourceManager.GetString("ErrorBackup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al ejecutar el borrado inicial con ID.
    '''</summary>
    Friend Shared ReadOnly Property ErrorBorradoSaldoInicial() As String
        Get
            Return ResourceManager.GetString("ErrorBorradoSaldoInicial", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al borrar la fila con ID {0}:.
    '''</summary>
    Friend Shared ReadOnly Property ErrorBorrarFilaID() As String
        Get
            Return ResourceManager.GetString("ErrorBorrarFilaID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al cargar los conceptos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCargarCON() As String
        Get
            Return ResourceManager.GetString("ErrorCargarCON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al cargar conceptos o cuentas en introducción.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCargarCONyCUE() As String
        Get
            Return ResourceManager.GetString("ErrorCargarCONyCUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al cargar las cuentas.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCargarCUE() As String
        Get
            Return ResourceManager.GetString("ErrorCargarCUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al cargar descripciones históricas.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCargarDescripciones() As String
        Get
            Return ResourceManager.GetString("ErrorCargarDescripciones", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error durante la eliminación en cascada.
    '''</summary>
    Friend Shared ReadOnly Property ErrorConceptoYRegistrosEliminados() As String
        Get
            Return ResourceManager.GetString("ErrorConceptoYRegistrosEliminados", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al consolidar conceptos nativo.
    '''</summary>
    Friend Shared ReadOnly Property ErrorConsolidarConceptos() As String
        Get
            Return ResourceManager.GetString("ErrorConsolidarConceptos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al consolidar cuentas nativo.
    '''</summary>
    Friend Shared ReadOnly Property ErrorConsolidarCuentas() As String
        Get
            Return ResourceManager.GetString("ErrorConsolidarCuentas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al generar la copia de seguridad.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCrearCopiaSeguridad() As String
        Get
            Return ResourceManager.GetString("ErrorCrearCopiaSeguridad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Crear Ruta.
    '''</summary>
    Friend Shared ReadOnly Property ErrorCrearRuta() As String
        Get
            Return ResourceManager.GetString("ErrorCrearRuta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al descargar la actualización.
    '''</summary>
    Friend Shared ReadOnly Property ErrorDescargarActualizacion() As String
        Get
            Return ResourceManager.GetString("ErrorDescargarActualizacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a revise su conexión a Internet o que el archivo no esté abierto.
    '''</summary>
    Friend Shared ReadOnly Property ErrorDescargarActualizacion2() As String
        Get
            Return ResourceManager.GetString("ErrorDescargarActualizacion2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al verificar duplicados.
    '''</summary>
    Friend Shared ReadOnly Property ErrorDuplicados() As String
        Get
            Return ResourceManager.GetString("ErrorDuplicados", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Ejecutar Saldo:.
    '''</summary>
    Friend Shared ReadOnly Property ErrorEjecutarSaldo() As String
        Get
            Return ResourceManager.GetString("ErrorEjecutarSaldo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al intentar eliminar el registro.
    '''</summary>
    Friend Shared ReadOnly Property ErrorEliminarRegistro() As String
        Get
            Return ResourceManager.GetString("ErrorEliminarRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al escanear vencimientos periódicos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorEscanearPeriodicos() As String
        Get
            Return ResourceManager.GetString("ErrorEscanearPeriodicos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al filtrar en pantalla.
    '''</summary>
    Friend Shared ReadOnly Property ErrorFiltrar() As String
        Get
            Return ResourceManager.GetString("ErrorFiltrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error General.
    '''</summary>
    Friend Shared ReadOnly Property ErrorGeneral() As String
        Get
            Return ResourceManager.GetString("ErrorGeneral", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al generar saldos iniciales.
    '''</summary>
    Friend Shared ReadOnly Property ErrorGenerarSaldoIniciales() As String
        Get
            Return ResourceManager.GetString("ErrorGenerarSaldoIniciales", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Grabar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ErrorGrabarRegistro() As String
        Get
            Return ResourceManager.GetString("ErrorGrabarRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Grabar en Temporal.
    '''</summary>
    Friend Shared ReadOnly Property ErrorGrabarTemporal() As String
        Get
            Return ResourceManager.GetString("ErrorGrabarTemporal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al leer importes mensuales.
    '''</summary>
    Friend Shared ReadOnly Property ErrorImportesMensuales() As String
        Get
            Return ResourceManager.GetString("ErrorImportesMensuales", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al inicializar los desplegables de edición periódica.
    '''</summary>
    Friend Shared ReadOnly Property ErrorIniciaDesplegables() As String
        Get
            Return ResourceManager.GetString("ErrorIniciaDesplegables", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al inicializar componentes independientes.
    '''</summary>
    Friend Shared ReadOnly Property ErrorIniciarComponentes() As String
        Get
            Return ResourceManager.GetString("ErrorIniciarComponentes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al inicializar los conceptos del presupuesto.
    '''</summary>
    Friend Shared ReadOnly Property ErrorIniciarConceptos() As String
        Get
            Return ResourceManager.GetString("ErrorIniciarConceptos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error Insertar Cero.
    '''</summary>
    Friend Shared ReadOnly Property ErrorInsertarCero() As String
        Get
            Return ResourceManager.GetString("ErrorInsertarCero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error Insertar Realidad.
    '''</summary>
    Friend Shared ReadOnly Property ErrorInsertarReal() As String
        Get
            Return ResourceManager.GetString("ErrorInsertarReal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al insertar los saldos iniciales.
    '''</summary>
    Friend Shared ReadOnly Property ErrorInsertarSaldos() As String
        Get
            Return ResourceManager.GetString("ErrorInsertarSaldos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al leer acumulado.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLeerAcumulado() As String
        Get
            Return ResourceManager.GetString("ErrorLeerAcumulado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error Leer Conceptos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLeerCON() As String
        Get
            Return ResourceManager.GetString("ErrorLeerCON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al leer el ejercicio.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLeerEjercicio() As String
        Get
            Return ResourceManager.GetString("ErrorLeerEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al leer históricos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLeerHistoricos() As String
        Get
            Return ResourceManager.GetString("ErrorLeerHistoricos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al limpiar la tabla Temporal.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLimpiarTemporal() As String
        Get
            Return ResourceManager.GetString("ErrorLimpiarTemporal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al llenar el Combo Descripción.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLlenarCmbDescripcion() As String
        Get
            Return ResourceManager.GetString("ErrorLlenarCmbDescripcion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al llenar Conceptos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLlenarConceptos() As String
        Get
            Return ResourceManager.GetString("ErrorLlenarConceptos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al llenar Cuentas.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLlenarCuentas() As String
        Get
            Return ResourceManager.GetString("ErrorLlenarCuentas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al localizar el concepto TRASPASO.
    '''</summary>
    Friend Shared ReadOnly Property ErrorLocalizarTraspaso() As String
        Get
            Return ResourceManager.GetString("ErrorLocalizarTraspaso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error crítico durante la Migración completa.
    '''</summary>
    Friend Shared ReadOnly Property ErrorMigracion() As String
        Get
            Return ResourceManager.GetString("ErrorMigracion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Migración Interrumpida.
    '''</summary>
    Friend Shared ReadOnly Property ErrorMigracionInterrumpida() As String
        Get
            Return ResourceManager.GetString("ErrorMigracionInterrumpida", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Modificar el Registro.
    '''</summary>
    Friend Shared ReadOnly Property ErrorModificarRegistro() As String
        Get
            Return ResourceManager.GetString("ErrorModificarRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error en la mutación de la BD clonada.
    '''</summary>
    Friend Shared ReadOnly Property ErrormutacionBDclonada() As String
        Get
            Return ResourceManager.GetString("ErrormutacionBDclonada", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al recuperar el identificador numérico del registro.
    '''</summary>
    Friend Shared ReadOnly Property ErrorRecuperarID() As String
        Get
            Return ResourceManager.GetString("ErrorRecuperarID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al refrescar el combo de conceptos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorRefrescarCON() As String
        Get
            Return ResourceManager.GetString("ErrorRefrescarCON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al refrescar el combo de cuentas.
    '''</summary>
    Friend Shared ReadOnly Property ErrorRefrescarCUE() As String
        Get
            Return ResourceManager.GetString("ErrorRefrescarCUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al rellenar el ListBox de conceptos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorRellenarListBox() As String
        Get
            Return ResourceManager.GetString("ErrorRellenarListBox", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al sincronizar el concepto.
    '''</summary>
    Friend Shared ReadOnly Property ErrorSincronizarCON() As String
        Get
            Return ResourceManager.GetString("ErrorSincronizarCON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error Grabar 1 (Interno).
    '''</summary>
    Friend Shared ReadOnly Property ErrorUpdate1() As String
        Get
            Return ResourceManager.GetString("ErrorUpdate1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error Grabar 2 (Interno).
    '''</summary>
    Friend Shared ReadOnly Property ErrorUpdate2() As String
        Get
            Return ResourceManager.GetString("ErrorUpdate2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Vaciar Apuntes.
    '''</summary>
    Friend Shared ReadOnly Property ErrorVaciarApuntes() As String
        Get
            Return ResourceManager.GetString("ErrorVaciarApuntes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Vaciar Periódicos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorVaciarPeriodicos() As String
        Get
            Return ResourceManager.GetString("ErrorVaciarPeriodicos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Vaciar Presupuestos.
    '''</summary>
    Friend Shared ReadOnly Property ErrorVaciarPresupuesto() As String
        Get
            Return ResourceManager.GetString("ErrorVaciarPresupuesto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error al Verificar la Integridad.
    '''</summary>
    Friend Shared ReadOnly Property ErrorVerificarIntegridad() As String
        Get
            Return ResourceManager.GetString("ErrorVerificarIntegridad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ESTETICA.
    '''</summary>
    Friend Shared ReadOnly Property ESTETICA() As String
        Get
            Return ResourceManager.GetString("ESTETICA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a La estructura de la base de datos se ha actualizado de manera integral a la nueva versión.
    '''</summary>
    Friend Shared ReadOnly Property EstructuraActualizada() As String
        Get
            Return ResourceManager.GetString("EstructuraActualizada", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ya existe en.
    '''</summary>
    Friend Shared ReadOnly Property Existe() As String
        Get
            Return ResourceManager.GetString("Existe", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Existentes.
    '''</summary>
    Friend Shared ReadOnly Property Existentes() As String
        Get
            Return ResourceManager.GetString("Existentes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Éxito.
    '''</summary>
    Friend Shared ReadOnly Property Exito() As String
        Get
            Return ResourceManager.GetString("Exito", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a FARMACIA.
    '''</summary>
    Friend Shared ReadOnly Property FARMACIA() As String
        Get
            Return ResourceManager.GetString("FARMACIA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fecha.
    '''</summary>
    Friend Shared ReadOnly Property Fecha() As String
        Get
            Return ResourceManager.GetString("Fecha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a FECHA.
    '''</summary>
    Friend Shared ReadOnly Property FECHA_UPPER() As String
        Get
            Return ResourceManager.GetString("FECHA_UPPER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fechas.
    '''</summary>
    Friend Shared ReadOnly Property Fechas() As String
        Get
            Return ResourceManager.GetString("Fechas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Filtrado).
    '''</summary>
    Friend Shared ReadOnly Property Filtrado() As String
        Get
            Return ResourceManager.GetString("Filtrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ha llegado al final de la tabla.
    '''</summary>
    Friend Shared ReadOnly Property FinalTabla() As String
        Get
            Return ResourceManager.GetString("FinalTabla", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a FONDO DE INVERSIÓN.
    '''</summary>
    Friend Shared ReadOnly Property FONDO_DE_INVERSION() As String
        Get
            Return ResourceManager.GetString("FONDO_DE_INVERSION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a GAS NATURAL.
    '''</summary>
    Friend Shared ReadOnly Property GAS_NATURAL() As String
        Get
            Return ResourceManager.GetString("GAS_NATURAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a GASOLINA.
    '''</summary>
    Friend Shared ReadOnly Property GASOLINA() As String
        Get
            Return ResourceManager.GetString("GASOLINA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Gastos.
    '''</summary>
    Friend Shared ReadOnly Property Gastos() As String
        Get
            Return ResourceManager.GetString("Gastos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a GASTOS BANCARIOS.
    '''</summary>
    Friend Shared ReadOnly Property GASTOS_BANCARIOS() As String
        Get
            Return ResourceManager.GetString("GASTOS_BANCARIOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Quieres guardar una Copia de Seguridad de la Base de Datos?.
    '''</summary>
    Friend Shared ReadOnly Property GuardarCopiaSeguridad() As String
        Get
            Return ResourceManager.GetString("GuardarCopiaSeguridad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a HACIENDA.
    '''</summary>
    Friend Shared ReadOnly Property HACIENDA() As String
        Get
            Return ResourceManager.GetString("HACIENDA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Hasta.
    '''</summary>
    Friend Shared ReadOnly Property Hasta() As String
        Get
            Return ResourceManager.GetString("Hasta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Importe.
    '''</summary>
    Friend Shared ReadOnly Property Importe() As String
        Get
            Return ResourceManager.GetString("Importe", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a IMPUESTO 1.
    '''</summary>
    Friend Shared ReadOnly Property IMPUESTO_1() As String
        Get
            Return ResourceManager.GetString("IMPUESTO_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a IMPUESTO 2.
    '''</summary>
    Friend Shared ReadOnly Property IMPUESTO_2() As String
        Get
            Return ResourceManager.GetString("IMPUESTO_2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a IMPUESTO 3.
    '''</summary>
    Friend Shared ReadOnly Property IMPUESTO_3() As String
        Get
            Return ResourceManager.GetString("IMPUESTO_3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a IMPUESTO 4.
    '''</summary>
    Friend Shared ReadOnly Property IMPUESTO_4() As String
        Get
            Return ResourceManager.GetString("IMPUESTO_4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a IMPUESTO 5.
    '''</summary>
    Friend Shared ReadOnly Property IMPUESTO_5() As String
        Get
            Return ResourceManager.GetString("IMPUESTO_5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Información.
    '''</summary>
    Friend Shared ReadOnly Property Informacion() As String
        Get
            Return ResourceManager.GetString("Informacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ingresos.
    '''</summary>
    Friend Shared ReadOnly Property Ingresos() As String
        Get
            Return ResourceManager.GetString("Ingresos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a INTERESES.
    '''</summary>
    Friend Shared ReadOnly Property INTERESES() As String
        Get
            Return ResourceManager.GetString("INTERESES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir a Hoy.
    '''</summary>
    Friend Shared ReadOnly Property IrAHoy() As String
        Get
            Return ResourceManager.GetString("IrAHoy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a JARDIN.
    '''</summary>
    Friend Shared ReadOnly Property JARDIN() As String
        Get
            Return ResourceManager.GetString("JARDIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a LUZ.
    '''</summary>
    Friend Shared ReadOnly Property LUZ() As String
        Get
            Return ResourceManager.GetString("LUZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Meses.
    '''</summary>
    Friend Shared ReadOnly Property Meses() As String
        Get
            Return ResourceManager.GetString("Meses", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Moneda.
    '''</summary>
    Friend Shared ReadOnly Property Moneda() As String
        Get
            Return ResourceManager.GetString("Moneda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Está completamente seguro de que desea eliminar FÍSICAMENTE de la Base de Datos los {0} apuntes seleccionados?.
    '''</summary>
    Friend Shared ReadOnly Property MsgConfirmarBorradoPlural() As String
        Get
            Return ResourceManager.GetString("MsgConfirmarBorradoPlural", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Está completamente seguro de que desea eliminar FÍSICAMENTE de la Base de Datos el apunte seleccionado?.
    '''</summary>
    Friend Shared ReadOnly Property MsgConfirmarBorradoSingular() As String
        Get
            Return ResourceManager.GetString("MsgConfirmarBorradoSingular", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay ninguna Coincidencia con los datos Introducidos.
    '''</summary>
    Friend Shared ReadOnly Property MsgDatos1() As String
        Get
            Return ResourceManager.GetString("MsgDatos1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay más Registros que Coincidan con los datos Introducidos.
    '''</summary>
    Friend Shared ReadOnly Property MsgDatos2() As String
        Get
            Return ResourceManager.GetString("MsgDatos2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Formato de fecha no válido.
    '''</summary>
    Friend Shared ReadOnly Property MsgErrorFecha() As String
        Get
            Return ResourceManager.GetString("MsgErrorFecha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fila Primera Seleccionada.
    '''</summary>
    Friend Shared ReadOnly Property MsgFila1() As String
        Get
            Return ResourceManager.GetString("MsgFila1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Fila Ultima Seleccionada.
    '''</summary>
    Friend Shared ReadOnly Property MsgFila2() As String
        Get
            Return ResourceManager.GetString("MsgFila2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Operación completada. Se han eliminado {0} registros físicos de la Base de Datos.
    '''</summary>
    Friend Shared ReadOnly Property MsgLoteEliminadoExito() As String
        Get
            Return ResourceManager.GetString("MsgLoteEliminadoExito", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Su periodo de prueba de 30 días ha finalizado. Por favor,
    '''adquiera la versión completa en la Microsoft Store..
    '''</summary>
    Friend Shared ReadOnly Property MsgPeriodoPruebaExpirado() As String
        Get
            Return ResourceManager.GetString("MsgPeriodoPruebaExpirado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Por favor, seleccione primero las filas que desea eliminar utilizando las celdas de la izquierda.
    '''</summary>
    Friend Shared ReadOnly Property MsgSeleccionarFilasEliminar() As String
        Get
            Return ResourceManager.GetString("MsgSeleccionarFilasEliminar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No.
    '''</summary>
    Friend Shared ReadOnly Property NO() As String
        Get
            Return ResourceManager.GetString("NO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No estas conectado a una red para comprobar nueva Versión.
    '''</summary>
    Friend Shared ReadOnly Property NoConectadoRed() As String
        Get
            Return ResourceManager.GetString("NoConectadoRed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se conectó por.
    '''</summary>
    Friend Shared ReadOnly Property NoConectoPor() As String
        Get
            Return ResourceManager.GetString("NoConectoPor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No es puede crear una descripción con el nombre.
    '''</summary>
    Friend Shared ReadOnly Property NoDescripcionSaldo() As String
        Get
            Return ResourceManager.GetString("NoDescripcionSaldo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se puede editar un apunte fuera del ejercicio actual.
    '''</summary>
    Friend Shared ReadOnly Property NoEditarFueraEjercicio() As String
        Get
            Return ResourceManager.GetString("NoEditarFueraEjercicio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se encontró el registro para actualizar.
    '''</summary>
    Friend Shared ReadOnly Property NoEncuentraRegistro() As String
        Get
            Return ResourceManager.GetString("NoEncuentraRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No existen registros del.
    '''</summary>
    Friend Shared ReadOnly Property NoExistenRegistros() As String
        Get
            Return ResourceManager.GetString("NoExistenRegistros", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a NO hay Datos en.
    '''</summary>
    Friend Shared ReadOnly Property NoHayDatos() As String
        Get
            Return ResourceManager.GetString("NoHayDatos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No hay datos históricos en años anteriores para generar saldos iniciales.
    '''</summary>
    Friend Shared ReadOnly Property NoHayDatosHistoricos() As String
        Get
            Return ResourceManager.GetString("NoHayDatosHistoricos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Nombre.
    '''</summary>
    Friend Shared ReadOnly Property Nombre() As String
        Get
            Return ResourceManager.GetString("Nombre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Notas.
    '''</summary>
    Friend Shared ReadOnly Property Notas() As String
        Get
            Return ResourceManager.GetString("Notas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Numero.
    '''</summary>
    Friend Shared ReadOnly Property Numero() As String
        Get
            Return ResourceManager.GetString("Numero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cantidad Cobros.
    '''</summary>
    Friend Shared ReadOnly Property NumeroCobros() As String
        Get
            Return ResourceManager.GetString("NumeroCobros", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cantidad Pagos.
    '''</summary>
    Friend Shared ReadOnly Property NumeroPagos() As String
        Get
            Return ResourceManager.GetString("NumeroPagos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a OCIO.
    '''</summary>
    Friend Shared ReadOnly Property OCIO() As String
        Get
            Return ResourceManager.GetString("OCIO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a OPENBANK.
    '''</summary>
    Friend Shared ReadOnly Property OPENBANK() As String
        Get
            Return ResourceManager.GetString("OPENBANK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Origen.
    '''</summary>
    Friend Shared ReadOnly Property Origen() As String
        Get
            Return ResourceManager.GetString("Origen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Página.
    '''</summary>
    Friend Shared ReadOnly Property Pagina() As String
        Get
            Return ResourceManager.GetString("Pagina", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a PENSION.
    '''</summary>
    Friend Shared ReadOnly Property PENSION() As String
        Get
            Return ResourceManager.GetString("PENSION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Periodo de Prueba Expirado.
    '''</summary>
    Friend Shared ReadOnly Property PeriodoPrueba() As String
        Get
            Return ResourceManager.GetString("PeriodoPrueba", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a PLAN PENSIONES.
    '''</summary>
    Friend Shared ReadOnly Property PLAN_DE_PENSIONES() As String
        Get
            Return ResourceManager.GetString("PLAN_DE_PENSIONES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CUENTA PLAN PENSIONES.
    '''</summary>
    Friend Shared ReadOnly Property PLAN_PENSIONES() As String
        Get
            Return ResourceManager.GetString("PLAN_PENSIONES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Deseas imprimir el gráfico en orientación Horizontal?.
    '''</summary>
    Friend Shared ReadOnly Property PreguntaHorizontal() As String
        Get
            Return ResourceManager.GetString("PreguntaHorizontal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Presupuestado.
    '''</summary>
    Friend Shared ReadOnly Property Presupuestado() As String
        Get
            Return ResourceManager.GetString("Presupuestado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a se procederá a instalarla. Pulsa Aceptar para continuar.
    '''</summary>
    Friend Shared ReadOnly Property ProcederaInstalar() As String
        Get
            Return ResourceManager.GetString("ProcederaInstalar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Realidad.
    '''</summary>
    Friend Shared ReadOnly Property Realidad() As String
        Get
            Return ResourceManager.GetString("Realidad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El registro ha sido borrado correctamente.
    '''</summary>
    Friend Shared ReadOnly Property RegistroBorrado() As String
        Get
            Return ResourceManager.GetString("RegistroBorrado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a El registro no se pudo borrar. Verifique.
    '''</summary>
    Friend Shared ReadOnly Property RegistroNoBorradoVerificar() As String
        Get
            Return ResourceManager.GetString("RegistroNoBorradoVerificar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a REGULARIZACION 1.
    '''</summary>
    Friend Shared ReadOnly Property REGULARIZACION_1() As String
        Get
            Return ResourceManager.GetString("REGULARIZACION_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a REGULARIZACION 2.
    '''</summary>
    Friend Shared ReadOnly Property REGULARIZACION_2() As String
        Get
            Return ResourceManager.GetString("REGULARIZACION_2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ROPA.
    '''</summary>
    Friend Shared ReadOnly Property ROPA() As String
        Get
            Return ResourceManager.GetString("ROPA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Saldo.
    '''</summary>
    Friend Shared ReadOnly Property Saldo() As String
        Get
            Return ResourceManager.GetString("Saldo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Saldo Inicial.
    '''</summary>
    Friend Shared ReadOnly Property SaldoInicial() As String
        Get
            Return ResourceManager.GetString("SaldoInicial", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Saldos iniciales generados e insertados correctamente.
    '''</summary>
    Friend Shared ReadOnly Property SaldosGeneradosExito() As String
        Get
            Return ResourceManager.GetString("SaldosGeneradosExito", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a SEGURO CASA.
    '''</summary>
    Friend Shared ReadOnly Property SEGURO_CASA() As String
        Get
            Return ResourceManager.GetString("SEGURO_CASA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a SEGURO COCHE.
    '''</summary>
    Friend Shared ReadOnly Property SEGURO_COCHE() As String
        Get
            Return ResourceManager.GetString("SEGURO_COCHE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a SEGURO MOTO.
    '''</summary>
    Friend Shared ReadOnly Property SEGURO_MOTO() As String
        Get
            Return ResourceManager.GetString("SEGURO_MOTO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Selecciona un Registro para Editar o Eliminar.
    '''</summary>
    Friend Shared ReadOnly Property SeleccionaRegistro() As String
        Get
            Return ResourceManager.GetString("SeleccionaRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Seleccione su idioma preferido para el manual de ayuda.
    '''</summary>
    Friend Shared ReadOnly Property SeleccioneIdiomaAyuda() As String
        Get
            Return ResourceManager.GetString("SeleccioneIdiomaAyuda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Separador Decimal.
    '''</summary>
    Friend Shared ReadOnly Property SeparadorDecimal() As String
        Get
            Return ResourceManager.GetString("SeparadorDecimal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Sí.
    '''</summary>
    Friend Shared ReadOnly Property SI() As String
        Get
            Return ResourceManager.GetString("SI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Sin Filtrar).
    '''</summary>
    Friend Shared ReadOnly Property SinFiltrar() As String
        Get
            Return ResourceManager.GetString("SinFiltrar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Solo admite el . Punto como separador decimal.
    '''</summary>
    Friend Shared ReadOnly Property SoloAdmitePunto() As String
        Get
            Return ResourceManager.GetString("SoloAdmitePunto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TARJETA DE CRÉDITO.
    '''</summary>
    Friend Shared ReadOnly Property TARJETA_DE_CREDITO() As String
        Get
            Return ResourceManager.GetString("TARJETA_DE_CREDITO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TELEFONO.
    '''</summary>
    Friend Shared ReadOnly Property TELEFONO() As String
        Get
            Return ResourceManager.GetString("TELEFONO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Tipo.
    '''</summary>
    Friend Shared ReadOnly Property Tipo() As String
        Get
            Return ResourceManager.GetString("Tipo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ESPECIAL.
    '''</summary>
    Friend Shared ReadOnly Property Tipo_Especial() As String
        Get
            Return ResourceManager.GetString("Tipo_Especial", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a GASTO.
    '''</summary>
    Friend Shared ReadOnly Property Tipo_Gasto() As String
        Get
            Return ResourceManager.GetString("Tipo_Gasto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a INGRESO.
    '''</summary>
    Friend Shared ReadOnly Property Tipo_Ingreso() As String
        Get
            Return ResourceManager.GetString("Tipo_Ingreso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TRASPASO.
    '''</summary>
    Friend Shared ReadOnly Property Tipo_Traspaso() As String
        Get
            Return ResourceManager.GetString("Tipo_Traspaso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Consejo Práctico:
    '''Para obtener una visualización óptima, nítida
    '''y detallada de tus gráficos, te recomendamos
    '''acotar el rango mediante los filtros de fechas,
    '''cuentas o seleccionando conceptos específicos
    '''en el listado (Embudo Rosa).
    '''¡Menos datos ofrecen un análisis mucho más claro!.
    '''</summary>
    Friend Shared ReadOnly Property TipoGrafico() As String
        Get
            Return ResourceManager.GetString("TipoGrafico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mis Cuentas con .
    '''</summary>
    Friend Shared ReadOnly Property TitolApp() As String
        Get
            Return ResourceManager.GetString("TitolApp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Borrado Finalizado.
    '''</summary>
    Friend Shared ReadOnly Property TituloBorradoFinalizado() As String
        Get
            Return ResourceManager.GetString("TituloBorradoFinalizado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Orientación de página.
    '''</summary>
    Friend Shared ReadOnly Property TituloPregunta() As String
        Get
            Return ResourceManager.GetString("TituloPregunta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Listado de Conceptos Contables.
    '''</summary>
    Friend Shared ReadOnly Property TituloReporteConceptos() As String
        Get
            Return ResourceManager.GetString("TituloReporteConceptos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Todos los Campos.
    '''</summary>
    Friend Shared ReadOnly Property Todos_Los_Campos() As String
        Get
            Return ResourceManager.GetString("Todos_Los_Campos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aceptar y Salir.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAceptar() As String
        Get
            Return ResourceManager.GetString("ToolTipAceptar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Añadir Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAñadir() As String
        Get
            Return ResourceManager.GetString("ToolTipAñadir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Anterior Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAnterior() As String
        Get
            Return ResourceManager.GetString("ToolTipAnterior", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Aplica el filtro a los Registros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipAplicarFiltro() As String
        Get
            Return ResourceManager.GetString("ToolTipAplicarFiltro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Buscar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipBuscar() As String
        Get
            Return ResourceManager.GetString("ToolTipBuscar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Activar la Calculadora.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipCalculadora() As String
        Get
            Return ResourceManager.GetString("ToolTipCalculadora", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cancelar.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipCancelar() As String
        Get
            Return ResourceManager.GetString("ToolTipCancelar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Editar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEditar() As String
        Get
            Return ResourceManager.GetString("ToolTipEditar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eliminar Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEliminar() As String
        Get
            Return ResourceManager.GetString("ToolTipEliminar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Eliminar Presupuestos mensuales del Concepto seleccionado.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEliminarPresupuesto() As String
        Get
            Return ResourceManager.GetString("ToolTipEliminarPresupuesto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Suprimir las Filas Seleccionadas de la Parrilla
    '''No se Eliminan de la Base de Datos.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipEliminaSeleccion() As String
        Get
            Return ResourceManager.GetString("ToolTipEliminaSeleccion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Refrescar la Parrilla Apuntes y Quitar Filtros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipF6() As String
        Get
            Return ResourceManager.GetString("ToolTipF6", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mostrar Gráficos.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipGraficos() As String
        Get
            Return ResourceManager.GetString("ToolTipGraficos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mostrar Gráficos 2D.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipGraficos2D() As String
        Get
            Return ResourceManager.GetString("ToolTipGraficos2D", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Mostrar Gráficos 3D.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipGraficos3D() As String
        Get
            Return ResourceManager.GetString("ToolTipGraficos3D", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Imprimir.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipImprimir() As String
        Get
            Return ResourceManager.GetString("ToolTipImprimir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Primer Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipPrimero() As String
        Get
            Return ResourceManager.GetString("ToolTipPrimero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Quitar el filtro a los Registros.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipQuitarFiltro() As String
        Get
            Return ResourceManager.GetString("ToolTipQuitarFiltro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Salir/Cerrar Ventana.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSalir() As String
        Get
            Return ResourceManager.GetString("ToolTipSalir", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Pulsar para Seguir Buscando o F3.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSeguirBuscando() As String
        Get
            Return ResourceManager.GetString("ToolTipSeguirBuscando", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Siguiente Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipSiguiente() As String
        Get
            Return ResourceManager.GetString("ToolTipSiguiente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Ir al Ultimo Registro.
    '''</summary>
    Friend Shared ReadOnly Property ToolTipUltimo() As String
        Get
            Return ResourceManager.GetString("ToolTipUltimo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TOTAL.
    '''</summary>
    Friend Shared ReadOnly Property TOTAL() As String
        Get
            Return ResourceManager.GetString("TOTAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Total Gastos.
    '''</summary>
    Friend Shared ReadOnly Property TotalGastos() As String
        Get
            Return ResourceManager.GetString("TotalGastos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Total Ingresos.
    '''</summary>
    Friend Shared ReadOnly Property TotalIngresos() As String
        Get
            Return ResourceManager.GetString("TotalIngresos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a TRASPASO.
    '''</summary>
    Friend Shared ReadOnly Property TRASPASO() As String
        Get
            Return ResourceManager.GetString("TRASPASO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Sin Programar...
    '''</summary>
    Friend Shared ReadOnly Property Vacio() As String
        Get
            Return ResourceManager.GetString("Vacio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Validación.
    '''</summary>
    Friend Shared ReadOnly Property Validación() As String
        Get
            Return ResourceManager.GetString("Validación", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a VARIOS.
    '''</summary>
    Friend Shared ReadOnly Property VARIOS() As String
        Get
            Return ResourceManager.GetString("VARIOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a VEHICULOS.
    '''</summary>
    Friend Shared ReadOnly Property VEHICULOS() As String
        Get
            Return ResourceManager.GetString("VEHICULOS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión.
    '''</summary>
    Friend Shared ReadOnly Property Versio() As String
        Get
            Return ResourceManager.GetString("Versio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión disponible:.
    '''</summary>
    Friend Shared ReadOnly Property VersionDisponible() As String
        Get
            Return ResourceManager.GetString("VersionDisponible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión de evaluación. Quedan.
    '''</summary>
    Friend Shared ReadOnly Property VersionEvaluacion() As String
        Get
            Return ResourceManager.GetString("VersionEvaluacion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Versión Instalada:.
    '''</summary>
    Friend Shared ReadOnly Property VersionInstalada() As String
        Get
            Return ResourceManager.GetString("VersionInstalada", resourceCulture)
        End Get
    End Property
End Class
